config/routes.rb
Rails.application.routes.draw do
  root 'tops#index'

  resources :items, only: [:index, :create, :update, :destroy] do
    post :update_all_position, on: :collection
  end

  resources :categories, only: [:index, :create, :destroy] do
    delete :destroy_all_items, on: :member
  end
  resources :users, only: %i[new create]

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  has_many :categories, dependent: :destroy
  has_many :items, dependent: :destroy

  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :name, presence: true, length: { maximum: 255 }
  validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :require_login
  add_flash_types :success, :error

  private

  def not_authenticated
    redirect_to login_path
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ActionController::API
  def index
    categories = current_user.categories.all.order(created_at: :asc)
    render json: categories.as_json(only: [:id, :name])
  end

  def create
    category = current_user.categories.new(category_params)
    if category.save
      render json: { message: '保存が成功しました', category: category.as_json(only: [:id, :name]) }, status: :ok
    else
      render json: { error: '保存に失敗しました' }, status: :unprocessable_entity
    end
  end

  def destroy
    category = Category.find(params[:id])
    if category.destroy
      render json: { message: '削除が成功しました' }, status: :ok
    else
      render json: { error: '削除に失敗しました' }, status: :unprocessable_entity
    end
  end

  def destroy_all_items
    category = Category.find(params[:id])

    if destroy_items(category.items)
      render json: { message: '削除が成功しました' }, status: :ok
    else
      render json: { error: '削除に失敗しました' }, status: :unprocessable_entity
    end
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

  def destroy_items(items)
    Item.transaction do
      items.each do |item_data|
        item = Item.find(item_data['id'])
        item.destroy!
      end
    rescue => e
      Rails.logger.error "Failed to destroy items: #{e.message}"
      return false
    end
    true
  end
end

app/controllers/items_controller.rb
class ItemsController < ActionController::API
  def index
    items = current_user.items.includes(:category)
    render json: items
  end

  def create
    category_id = item_params[:category_id]
    category = current_user.categories.find_by(id: category_id)

    unless category
      return render json: { error: '無効なカテゴリです' }, status: :unprocessable_entity
    end

    last_item_position = category.items.maximum(:position) || 0
    new_item_position = last_item_position + 1
    item = current_user.items.new(item_params.except(:category_id).merge(category: category, position: new_item_position))
    if item.save
      render json: { message: '保存が成功しました', item: item }, status: :ok
    else
      render json: { error: '保存に失敗しました' }, status: :unprocessable_entity
    end
  end

  def update
    item = current_user.items.find(params[:id])
    if item.update(item_params)
      render json: { message: '更新が成功しました', item: item }, status: :ok
    else
      render json: { error: '更新に失敗しました' }, status: :unprocessable_entity
    end
  end

  def destroy
    item = current_user.items.find(params[:id])
    if item.destroy
      render json: { message: '削除が成功しました' }, status: :ok
    else
      render json: { error: '削除に失敗しました' }, status: :unprocessable_entity
    end
  end

  def update_all_position
    updated_items = params[:items]
    if update_items_position(updated_items)
      render json: { message: '更新が成功しました' }, status: :ok
    else
      render json: { error: '更新に失敗しました' }, status: :unprocessable_entity
    end
  end

  private

  def item_params
    params.require(:item).permit(:title, :content, :assignee, :category_id)
  end

  def update_items_position(items)
    Item.transaction do
      items.each do |item_data|
        item = Item.find(item_data['id'])
        category = Category.find(item_data['category_id'])
        item.update!(category_id: category.id, position: item_data['position'])
      end
    rescue => e
      Rails.logger.error "Failed to update items: #{e.message}"
      return false
    end
    true
  end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  def index; end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_action :require_login, only: %i[new create]

  def new; end

  def create
    @user = login(params[:email], params[:password])

    if @user
      redirect_to root_path, success: "ログインしました"
    else
      flash.now[:error] = "ログインに失敗しました"
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    logout
    redirect_to root_path, status: :see_other, error: "ログアウトしました"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: %i[new create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      auto_login(@user)
      redirect_to root_path , success: "ユーザー登録が完了しました"
    else
      flash.now[:error] = "ユーザー登録に失敗しました"
      render :new, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RUNTEQHub</title>
    <%= favicon_link_tag 'favicon.ico' %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <div class="bg-base-200 h-screen">
      <%= render 'shared/header' %>
      <%= render 'shared/flash_message' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <div id="flash-message" role="alert" class="alert alert-<%= message_type %>">
    <%= message %>
  </div>
<% end %>

<script>
document.addEventListener('DOMContentLoaded', () => {
  setTimeout(() => {
    const flashMessage = document.getElementById('flash-message');
    if (flashMessage) {
      flashMessage.classList.add('hidden');
    }
  }, 5000); // 7秒後にフラッシュメッセージを非表示にする
});
</script>

app/views/shared/_header.html.erb
<div class="flex h-14 items-center bg-base-100">
  <div class="mx-4 flex-1"><%= link_to image_tag("RUNTEQHub_logo.png", class: "h-12"), root_path, data: { turbo: false } %></div>
  <% if logged_in? %>
    <div class="dropdown dropdown-end mx-4 cursor-pointer">
      <div tabindex="0">...</div>
      <ul
        tabindex="0"
        class="menu dropdown-content z-10 rounded-box border border-gray-300 bg-base-100 shadow"
      >
        <li><%= link_to 'ログアウト', logout_path, class: 'whitespace-nowrap', data: { turbo_method: :delete } %></li>
      </ul>
    </div>
  <% end %>
</div>

app/views/tops/index.html.erb
<div class="flex h-[93%] flex-col bg-base-200" id="todo_app"></div>

app/views/user_sessions/new.html.erb
<div class="h-[90%] bg-base-100 pt-5">
  <h2 class="mx-4 text-4xl font-bold">ログイン</h2>
  <%= form_with(url: login_path, data: { turbo: false }, method: :post) do |form| %>
    <div class="m-4">
      <%= form.label :email, class: "text-xl" %>
      <%= form.email_field :email, class: "mt-2 input input-bordered input-lg md:input-md w-full", placeholder: "メールアドレスを入力してください" %>
    </div>
    <div class="m-4">
      <%= form.label :password, class: "text-xl" %>
      <%= form.password_field :password, class: "mt-2 input input-bordered input-lg md:input-md w-full", placeholder: "パスワードを入力してください" %>
    </div>
    <div class="m-4">
      <%= form.submit "ログイン", class: "btn btn-primary" %>
    </div>
  <% end %>
  <div class="flex flex-col items-center justify-between">
    <%= link_to "登録ページへ", new_user_path, class: "text-blue-500 hover:text-blue-800" %>
  </div>
</div>

app/views/users/new.html.erb
<div class="bg-base-100 h-[90%] pt-5">
  <h2 class="text-4xl font-bold mx-4">ユーザー登録</h2>
  <%= form_with(model: @user, data: { turbo: false }, url: users_path, local: true) do |form| %>
    <div class="m-4">
      <%= form.label :name, class: "text-xl" %>
      <%= form.text_field :name, class: "mt-2 input input-bordered input-lg md:input-md w-full", placeholder: "名前を入力してください" %>
    </div>
    <div class="m-4">
      <%= form.label :email, class: "text-xl" %>
      <%= form.email_field :email, class: "mt-2 input input-bordered input-lg md:input-md w-full", placeholder: "メールアドレスを入力してください" %>
    </div>
    <div class="m-4">
      <%= form.label :password, class: "text-xl" %>
      <%= form.password_field :password, class: "mt-2 input input-bordered input-lg md:input-md w-full", placeholder: "パスワードを入力してください" %>
    </div>
    <div class="m-4">
      <%= form.submit "ユーザー登録", class: "btn btn-primary" %>
    </div>
  <% end %>
  <div class="flex flex-col items-center justify-between">
    <%= link_to "ログインページへ", login_path, class: "text-blue-500 hover:text-blue-800" %>
  </div>
</div>